# Generated by Django 5.0.7 on 2024-07-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('change_user_to_project', 'Can add or delete user to project')]},
        ),
    ]
